# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1bb2425bba2ff814e32a1cb9054af781b111f579957c756cca1e329e4c7e8b3d70af2bbc678acae8505d7057b1ada48ff0c5d04b97a9e80f5565eed2c230fc84

test:
  secret_key_base: 3e2b4c81bb0133f7119db6138705ddad0239c0886b002f6180934c32c44c3743da37d1af230e6830620baff7c735948e1fceeb14b272341b21119b2de5f2d2e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
